import { Inter } from 'next/font/google'
import {M_PLUS_Rounded_1c} from 'next/font/google'
import './globals.css'

const inter = M_PLUS_Rounded_1c({  weight: ["500", "700"],   

subsets: ["latin"],
variable: "--poppins-font",})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
